### ISSUE TITLE
Naming inconsistency of videos `GreenEggSep2021_*`

### ISSUE THREAD

**Issue by fabiocarrara** [sauterl/vbs23-mvk-snapshot#1]
Videos names usually contain an underscore separating place, date, and video number (e.g., `Lembeh_Jul2013_0001.mp4`),
but it seems an underscore is missing from the `GreenEggSep2021_*`  files (Should they be `GreenEgg_Sep2021_...`?).

It's not a big issue, but it would be nice if this is fixed; it would simplify info extraction from filenames (no regex, no problems😊).
Most importantly, which video id DRES will recognize? `GreenEggSep2021_*` or `GreenEgg_Sep2021_*` ?

**Comment by sauterl** [comment]
The following snipped was applied to the snapshot. To avaoid re-downloading you can apply them on your side as well.

DRES will use the proper format of `<location>_<MMMYYYY>_<video>` as submission input, if correctly set-up.

```bash
#!/bin/bash

mv $1/GreenEggSep2021_0001.mp4 $1/GreenEgg_Sep2021_0001.mp4
mv $1/GreenEggSep2021_0002.mp4 $1/GreenEgg_Sep2021_0002.mp4
mv $1/GreenEggSep2021_0003.mp4 $1/GreenEgg_Sep2021_0003.mp4
mv $1/GreenEggSep2021_0004.mp4 $1/GreenEgg_Sep2021_0004.mp4
mv $1/GreenEggSep2021_0005.mp4 $1/GreenEgg_Sep2021_0005.mp4
mv $1/GreenEggSep2021_0006.mp4 $1/GreenEgg_Sep2021_0006.mp4
mv $1/GreenEggSep2021_0007.mp4 $1/GreenEgg_Sep2021_0007.mp4
mv $1/GreenEggSep2021_0008.mp4 $1/GreenEgg_Sep2021_0008.mp4
mv $1/GreenEggSep2021_0009.mp4 $1/GreenEgg_Sep2021_0009.mp4
mv $1/GreenEggSep2021_0010.mp4 $1/GreenEgg_Sep2021_0010.mp4
mv $1/GreenEggSep2021_0011.mp4 $1/GreenEgg_Sep2021_0011.mp4
mv $1/GreenEggSep2021_0012.mp4 $1/GreenEgg_Sep2021_0012.mp4
mv $1/GreenEggSep2021_0013.mp4 $1/GreenEgg_Sep2021_0013.mp4
mv $1/GreenEggSep2021_0014.mp4 $1/GreenEgg_Sep2021_0014.mp4
mv $1/GreenEggSep2021_0015.mp4 $1/GreenEgg_Sep2021_0015.mp4
mv $1/GreenEggSep2021_0016.mp4 $1/GreenEgg_Sep2021_0016.mp4
mv $1/GreenEggSep2021_0017.mp4 $1/GreenEgg_Sep2021_0017.mp4
mv $1/GreenEggSep2021_0018.mp4 $1/GreenEgg_Sep2021_0018.mp4
mv $1/GreenEggSep2021_0019.mp4 $1/GreenEgg_Sep2021_0019.mp4
mv $1/GreenEggSep2021_0020.mp4 $1/GreenEgg_Sep2021_0020.mp4
mv $1/GreenEggSep2021_0021.mp4 $1/GreenEgg_Sep2021_0021.mp4
```

**Comment by fabiocarrara** [comment]
Thanks!
For completeness, I report that also files in `information/selected_frames/` and `information/thumbnails/` need to be renamed.

**Comment by fabiocarrara** [comment]
Thanks!
For completeness, I report that also the jpg files in the `information/thumbnails` folder should be renamed.

**Comment by sauterl** [comment]
Thank you for the information. I was under the impression that this particular issue was fixed in the original dataset. However, this is not relevant for DRES and thus, will be fixed in the next iteration (in case another issue was found).
